### ISSUE TITLE
Fix response plot X-axis

### ISSUE THREAD

**Issue by renatoparedes** [renatoparedes/scikit-neuromsi#2]
![image](https://user-images.githubusercontent.com/49348026/186819220-b4d52a57-cd46-4fb3-b765-1f087e5f9452.png)

El eje X del plot no se corresponde con las unidades de entrada en las que se especifica el estímulo. En la imagen se observa que las posiciones son 5 y -5, mientras que el plot las registra en 15 y 25.

**Comment by leliel12** [comment]
En todos los modelos

- Mover los rangos de modos al init, y brindar una property que los acceda
- Fijarse que no haya informarcion repetida entre el run y el init
- Los rangos se deben llamar `<modo>_range` y deben ser tuplas de dos elementos.

**Comment by renatoparedes** [comment]
Listo!
