### ISSUE TITLE
Changing parameter detection fails with NoneType run parameters

### ISSUE THREAD

**Issue by renatoparedes** [renatoparedes/scikit-neuromsi#4]
Este código:

```python
import numpy as np
from skneuromsi.neural import Paredes2022
from skneuromsi.cmp.sweep import ParameterSweep

dis = np.array([-24, -12, -6, -3, 3, 6, 12, 24])
model= Paredes2022(neurons=90, position_range=(0, 90))
sp = ParameterSweep(model=model, target="visual_position", repeat=2, n_jobs=-2, range=45 + dis)
res = sp.run(auditory_position=45, visual_sigma=2, auditory_sigma=10, noise=True)
res.causes.unity_report()
```

Bota el error:

![image](https://github.com/renatoparedes/scikit-neuromsi/assets/49348026/e6ee25f9-934d-4d44-bd4c-3a24e4054b0e)

Esto es porque cuando calcula el "changing_parameters()" se encuentra conque el disparity matrix tiene parámetros con valores None. Creo que se puede solucionar si al método changin_parameters se le agrega una línea que excluya las columnas con parámeteros None.

**Comment by leliel12** [comment]
Estoy con esto, 

Se pueden hacer dos cosas distintas, una es tu sugerencia, la otra es dejar que nan se ordene con argsor (https://stackoverflow.com/a/21190090/2489206)

**Comment by leliel12** [comment]
unique -> set
